### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by zf-666** [rover-xingyu/L2G-NeRF#1]
您好，感谢您的工作。
我在复现的时候遇到了一些问题，有关warp网络的初始化，和它的激活函数。想问一下是怎么设置的？
再次感谢！

**Comment by rover-xingyu** [comment]
Thanks for your interest! We use the kaiming_uniform_ initialization and the relu activation function for the warp field.

**Comment by Linxius** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
