### ISSUE TITLE
When the code will be released

### ISSUE THREAD

**Issue by xiazhi1** [rover-xingyu/L2G-NeRF#2]
Hi! Thanks for your awesome work ! I want to know when the code will be released . I can not wait to test your wodenful work!!!

**Comment by karanchahal** [comment]
yeah I would like to use it as well

**Comment by Nemo1999** [comment]
Please release the code!!!

**Comment by Ghul-huan** [comment]
paper is cheap ,show me the code

**Comment by karanchahal** [comment]
maybe this paper is generated by gpt, no sign of code

**Comment by rover-xingyu** [comment]
Thank you all for being so interested. Though we understand your eagerness to play with L2G-NeRF, we are busy with other projects now. The code will be released during the CVPR conference. Let's look forward to it!

**Comment by rover-xingyu** [comment]
The code has been released now. Enjoy coding!
