### ISSUE TITLE
Missing initialization for warp_embedding and warp_mlp

### ISSUE THREAD

**Issue by Nemo1999** [rover-xingyu/L2G-NeRF#4]
Thanks for releasing the code, I really appreciate your work! 

I tried to run the code with `l2g_nerf` model, and the value of taylor series shoots to +/-infinity in `camera.se3_to_SE3` .

It seems that this is caused by the `warp_mlp` giving very large (about 100~1000) se3 values without initialization.

How should I initialize `warp_mlp` and `warp_embedding`? Or did I miss anything? 

Thanks :)

**Comment by rover-xingyu** [comment]
Thanks for your interest! Please share the command you use for us to reproduce the issue.

**Comment by Nemo1999** [comment]
Problem Solved !

It's my mistake, I passed the wrong intrinsic matix ( inverted one)

**Comment by Nemo1999** [comment]
Thanks for the timely responce !
