### ISSUE TITLE
Translation errors are scaled by 100.

### ISSUE THREAD

**Issue by TwiceMao** [rover-xingyu/L2G-NeRF#8]
What do you mean by Translation errors are scaled by 100.?
I want to know the unit of translation errors?
Is it meter?

**Comment by rover-xingyu** [comment]
Hi, as we use Procrustes analysis to align the optimized poses to the GT camera poses before evaluating registration quality, the unit of translation errors is determined by the GT camera poses of datasets. Translation errors are multiplied by 100 for easy visual comparison.
